### PR TITLE
fix(ps,bsd): save backup language + consistency

### LINKED ISSUE #2325: Scanners: change copy to "Saving Backup" and prevent closing backup flow

### PR DESCRIPTION
**Pull request by adghayes**
## Overview
Closes #2325. Also fixes the export --> save language for backups only, as part of #1443.

### CODE REVIEW

File: frontends/precinct-scanner/src/components/export_backup_modal.tsx [hunk 1]
```diff
@@ -166,7 +166,7 @@ export function ExportBackupModal({ onClose, usbDrive }: Props): JSX.Element {
   }
 
   if (currentState === ModalState.SAVING) {
-    return <Modal content={<Loading />} onOverlayClick={onClose} />;
+    return <Modal content={<Loading>Saving Backup</Loading>} />;
```
Comment (adghayes) [inline frontends/precinct-scanner/src/components/export_backup_modal.tsx:169]: Here is the only non-copy change of the PR. Actually adding copy ("Saving Backup") rather than "Loading", and preventing close by overlay click.

Comment (arsalansufi) [reply frontends/precinct-scanner/src/components/export_backup_modal.tsx:169]: Thanks for pointing this out!

**Review by arsalansufi — APPROVED** [review]
:ship:
