### PR TITLE
fix(pdi-scanner): use a smaller USB buffer in development

### LINKED ISSUE #5541: Toggle PDI buffer size given NODE_ENV so that dev works out the box
https://votingworks.slack.com/archives/CEL6D3GAD/p1724091885793609?thread_ts=1724091717.787029&channel=CEL6D3GAD&message_ts=1724091885.793609

### PR DESCRIPTION
**Pull request by eventualbuddha**
## Overview

Closes #5541

## Demo Video or Screenshot

```
❯ cargo run --example scan_forever --release
   Compiling pdi-scanner v0.1.0 (/media/parallels/WorkingFiles/code/vxsuite/libs/pdi-scanner)
    Finished `release` profile [optimized] target(s) in 1.53s
     Running `/media/parallels/WorkingFiles/code/vxsuite/target/release/examples/scan_forever`
waiting for sheet…
event: BeginScanEvent
event: EndScanEvent
Saved images from scan:
- Top: scan-0000-top.png
- Bottom: scan-0000-bottom.png
waiting for sheet…
^Creceived SIGINT
exiting

❯ NODE_ENV=production cargo run --example scan_forever --release
   Compiling pdi-scanner v0.1.0 (/media/parallels/WorkingFiles/code/vxsuite/libs/pdi-scanner)
    Finished `release` profile [optimized] target(s) in 3.28s
     Running `/media/parallels/WorkingFiles/code/vxsuite/target/release/examples/scan_forever`
Error: 
   0: failed to receive: timed out waiting on channel
   1: timed out waiting on channel

Location:
   libs/pdi-scanner/examples/scan_forever.rs:66

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

## Testing Plan
See above.

### CODE REVIEW

File: libs/pdi-scanner/build.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+fn main() {
+    println!("cargo::rustc-check-cfg=cfg(production)");
+    println!("cargo:rerun-if-env-changed=NODE_ENV");
+
+    let is_production = match std::env::var("NODE_ENV") {
+        Ok(env) => env == "production",
+        Err(_) => false,
+    };
```
Comment (arsalansufi) [inline libs/pdi-scanner/build.rs:8]: One thing I'm unsure about is whether we also need to consider whether this is a VxDev setup vs. true prod. On VxDev, `NODE_ENV` is `production`, but `REACT_APP_VX_DEV` is set to `true` so that we can distinguish it from true prod, e.g.

https://github.com/votingworks/vxsuite/blob/0d0e272ba8aab6e61f5c43d5dcdc875b423a1738/libs/auth/src/config.ts#L24-L26

My quick sense is that, since VxDev isn't using VMs, it doesn't need the smaller buffer.

So all probably fine as is, just wanted to flag

**Review by arsalansufi — APPROVED** [review]
LGTM!

File: libs/pdi-scanner/build.rs (hunk 1 above)
Comment (eventualbuddha) [reply libs/pdi-scanner/build.rs:8]: Let's do the simpler version to start. If it turns out VxDev doesn't work, we can update it.

Comment (arsalansufi) [reply libs/pdi-scanner/build.rs:8]: Yup sounds right to me!
