### PR TITLE
VxCentralScan: limit imprinter string to 40 characters for fi-8950

### LINKED ISSUE #8053: VxCentralScan: enable fi-8950 imprinting
We have an imprinter installed on the fi-8950 and have confirmed it works via Ricoh utilities. It is not working with our existing software - maybe `libsane` doesn't support it, maybe we need to use a different part of the API, etc.

This task is to get imprinting to work on the fi-8950 just as it does on the fi-8170 and the fi-7600.

### PR DESCRIPTION
**Pull request by kshen0**
## Overview

Closes https://github.com/votingworks/vxsuite/issues/8053

The imprinter for fi-8950 scanner has a 40 character limit in the imprint command. The imprinter for the fi-8170 supports 43 characters. Our imprinter string was `<UUID>_%04ud` or 42 characters, which means it worked on the 8170 but not 8950.

This PR truncates the UUID to `<first segment>-<last segment>_%04ud` eg. `12345678-abcdef123456-0005` for the 5th ballot in batch `12345678-...-abcdef123456`. It also hard caps the prefix to 34 characters so if we happen to migrate to an ID that isn't splittable by `-` we still can fallback safely.

## Demo Video or Screenshot

Videos of letter, legal, and 22" ballots. This was before the change from underscore to hyphen character as separator.

https://github.com/user-attachments/assets/81864532-d8f9-4b34-8924-de3e8389ec0a

https://github.com/user-attachments/assets/3be0eb23-0d87-436a-accd-84563a422c94

https://github.com/user-attachments/assets/a7ee750e-9631-47f6-9e7d-bb247fec6cc3

## Testing Plan

- manually tested on hardware
- added test for truncating logic

## Checklist

- [ ] I have prefixed my PR title with "VxDesign: ", "VxPollBook: ", or "HWTA: " if my change is specific to one of those products.
- [ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate for any new user actions.
- [x] I have added the "user-facing-change" label to this PR, if relevant, to automate an announcement in #machine-product-updates.

### CODE REVIEW

File: apps/central-scan/backend/src/fujitsu_scanner.ts [hunk 1]
```diff
@@ -163,13 +167,27 @@ export class FujitsuScanner implements BatchScanner {
       // streaming over USB and waiting for the bytes to cross the wire before
       // continuing. Verified that this improves performance with the fi-8170
       // from 1.3s to 0.8s per sheet along with `--prepick=ON`.
-      '--buffermode=ON',
+      // '--buffermode=ON',
```
Comment (kshen0) [inline apps/central-scan/backend/src/fujitsu_scanner.ts:172]: Temporary fix for a regression in the flow that prompts users to remove uninterpretable ballots - see https://votingworks.slack.com/archives/CEL6D3GAD/p1775852736739979

I think this is worth committing to `main` since the flow is unusable at the moment

File: apps/central-scan/backend/src/fujitsu_scanner.ts [hunk 2]
```diff
@@ -17,6 +17,12 @@ const debug = makeDebug('scan:scanner');
 export const FUJITSU_VENDOR_ID = 0x4c5;
 export const FUJITSU_FI_7160_PRODUCT_ID = 0x132e;
 export const FUJITSU_FI_8170_PRODUCT_ID = 0x15ff;
+const SEQUENTIAL_BALLOT_ID_STRING = '_%04ud';
+// The fi-8950 silently fails to imprint if the --endorserString option
```
Comment (kofi-q) [inline apps/central-scan/backend/src/fujitsu_scanner.ts:21]: Must've been so frustrating to debug 😅

**Review by kofi-q — APPROVED** [review]
✅

File: apps/central-scan/backend/src/fujitsu_scanner.ts (hunk 2 above)
Comment (kshen0) [reply apps/central-scan/backend/src/fujitsu_scanner.ts:21]: Definitely a headscratcher when the other model supports 43 characters
