### PR TITLE
fix(scan): improve the "delete batch" experience

### LINKED ISSUE #366: BSD: delete batch flickers

### PR DESCRIPTION
**Pull request by eventualbuddha**
Previously I had put in some code to quickly hide the batches that had been deleted while the server did the actual delete. However, this turned out to be flaky and would sometimes hide then show then hide the row. In practice deletes are really fast so having this optimization was not useful.

Additionally, the confirmation was using the built-in `confirm` function which doesn't provide a consistent UX with the rest of the application. This commit changes to use a `Modal` and to wait until the delete is confirmed to dismiss the modal.

|Prompt|With Error|
|-|-|
|image|image|

Closes #366

### CODE REVIEW

File: apps/bsd/src/screens/DashboardScreen.tsx [hunk 1]
```diff
@@ -116,6 +154,32 @@ const DashboardScreen: React.FC<Props> = ({
           <p>No ballots have been scanned.</p>
         )}
       </Prose>
+      {pendingDeleteBatchId && (
+        <Modal
+          centerContent
```
Comment (carolinemodic) [inline apps/bsd/src/screens/DashboardScreen.tsx:159]: nit but I usually add `onOverlayClick={cancelDeleteBatch}` to the Modal props which will allow the user to click outside the modal to dismiss it in addition to pressing the close button. It might complicate things here a bit though as you would only want to have that when its not in the "Deleting..." state.

**Review by carolinemodic — APPROVED** [review]

File: apps/bsd/src/screens/DashboardScreen.tsx (hunk 1 above)
Comment (eventualbuddha) [reply apps/bsd/src/screens/DashboardScreen.tsx:159]: Good suggestion, added.
