### PR TITLE
VxPollBook: update multi-precinct import logic

### LINKED ISSUE #7456: VxPollBook: trim zeros in ward identifiers when importing voters and streetNames files
the precinct validation logic bites again! for claremont, my initial poll book package failed on import because in their voter and street name files, the ward is “02” rather than “2" and we’re not trimming those zeros, so we just failed. luckily, I can just massage those files, doing a careful find and replace, without touching the election definition and messing up card compatibility

Issue automatically created from Slack feedback reported by drew: 
https://votingworks.slack.com/archives/C098ZSZ7719/p1761592515438229

### PR DESCRIPTION
**Pull request by adghayes**
## Overview

Closes #7456 and #7426. Handles district / ward numbers with leading zeros. Sets up different code paths for single and multi-precinct elections.

## Checklist

- [x] I have prefixed my PR title with "VxDesign: ", "VxPollBook: ", or "HWTA: " if my change is specific to one of those products.
- [ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate for any new user actions.
- [ ] I have added the "user_facing_change" label to this PR, if relevant, to automate an announcement in #machine-product-updates.

### CODE REVIEW

File: apps/pollbook/backend/src/pollbook_package.ts [hunk 1]
```diff
@@ -63,9 +63,32 @@ type PollbookPackageParseError =
...
+    }
+  | {
+      type: 'multi-precinct';
+      precinctIds: Record<string, string>;
+    };
+
+function trimZerosFromExternalPrecinctId(externalId: string): string {
+  const externalWardIdParseIntResult = safeParseInt(externalId);
+  if (externalWardIdParseIntResult.isErr()) {
+    throw new Error(`Non-numeric ward or district: ${externalId}`);
```
Comment (kshen0) [inline apps/pollbook/backend/src/pollbook_package.ts]: Are ward or district IDs ever alphanumeric?

Comment (adghayes) [reply apps/pollbook/backend/src/pollbook_package.ts]: in NH, they are always just numeric. this already doesn't apply to anywhere outside of NH, so I think it's OK to further tune it to NH
