### PR TITLE
Change File Transfer Language

### LINKED ISSUE #1443: VxSuite: change download/upload language
In a few spots, we use the terms "download" and "upload", which both is incorrect and feels incorrect. We're not uploading a ballot package. We're not downloading CVRs. We're loading a ballot package, we're saving CVRs. We should review our language accordingly.

/cc @beausmith @ginvdr for thoughts.

### PR DESCRIPTION
**Pull request by adghayes**
## Overview
Closes #1443. Changes all user-facing (including in logs) file transfer language to be consistent:
- `Export`, `Download` --> `Save`
- `Import`, `Upload` --> `Load`

Touches three apps - `bsd`, `election-manager`, `precinct-scanner`. Also touches logging.

All variable names were left intact to make this a less risky change, with the exception of the `LogEventId` enumeration. So please pay closer attention to `LogEventId`'s in code review.

One copy nit - the `Export Ballot Package` Button was changed to `Export Package` to save screen space, and is now `Save Package`, which seems too vague. Suggest `Export Ballot Package`? 

## Demo Video or Screenshot

Screen Shot 2022-08-12 at 1 48 57 PM
Screen Shot 2022-08-12 at 1 45 32 PM
Screen Shot 2022-08-12 at 1 45 43 PM
Screen Shot 2022-08-12 at 1 43 28 PM
Screen Shot 2022-08-12 at 1 43 16 PM
Screen Shot 2022-08-12 at 1 43 05 PM

## Checklist
- [ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced.
- [ ] I have added JSDoc comments to any newly introduced exports

- [ ] I have added a screenshot and/or video to this PR to demo the change
- [ ] I have added the "user_facing_change" label to this PR to automate an announcement in #machine-product-updates

### CODE REVIEW

File: libs/logging/src/log_event_ids.ts [hunk 1]
```diff
@@ -74,14 +74,14 @@ export enum LogEventId {
   ClearedBallotData = 'clear-ballot-data-complete',
   OverridingMarkThresholds = 'override-mark-threshold-init',
   OverrodeMarkThresholds = 'override-mark-thresholds-complete',
-  DownloadedScanImageBackup = 'download-backup-scan-images',
+  SavedScanImageBackup = 'saved-backup-scan-images',
```
Comment (arsalansufi) [inline libs/logging/src/log_event_ids.ts:77]: I see this discrepancy was already here so feel free to ignore! But could be nice to make the variable name and string match up:

```
SavedScanImageBackup = 'saved-scan-image-backup'
```

**Review by arsalansufi — APPROVED** [review]
Love the consistency! LGTM!

File: libs/logging/src/log_event_ids.ts (hunk 1 above)
Comment (adghayes) [reply libs/logging/src/log_event_ids.ts]: tweaked
