### PR TITLE
fix(ps): sync cvr export to disk

### LINKED ISSUE #1981: VxScan: no CVR saved on polls closed
This issue was observed during L&A in Warren and reproduced on a locked-down production imaged VxScan.

CVR files are not saved to USB disk after polls are closed, but they are still saved if you either 1) power down the machine before ejection or 2) export CVRs through the admin card screen.

### Repro steps
1. Scan ballots
2. Insert poll worker card and close polls
3. Remove USB
4. No CVR files will be saved

### PR DESCRIPTION
**Pull request by adghayes**
## Overview
Closes #1981. When saving CVRs - whether on polls closed or when exporting from the Admin menu - forces the machine to finish writing the file to disk by calling the `sync` command. This prevents the CVR file from not being saved or being saved improperly. It does slightly increase the delay when closing polls, by a couple of seconds, but that tradeoff is easily worth it.

Depends on [votingworks/kiosk-browser#129](https://github.com/votingworks/kiosk-browser/pull/129) to introduce the `kiosk.syncUsbDrive` API. 

Sidebar: the precinct scanner poll worker flow lacks any logging. Not sure if that's intentional, but I didn't touch it in this PR. 

## Testing Plan
- Manual testing on hardware
- Unit test for `usbstick` util

## Checklist
- [ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced.
- [ ] I have added JSDoc comments to any newly introduced exports

### CODE REVIEW

File: libs/utils/src/usbstick.ts [hunk 1]
```diff
@@ -61,3 +61,13 @@ export async function doUnmount(): Promise<void> {
   await window.kiosk.unmountUsbDrive(device.deviceName);
   return await sleep(FLUSH_IO_DELAY_MS);
 }
+
+export async function doSync(): Promise<void> {
```
Comment (jonahkagan) [inline libs/utils/src/usbstick.ts:65]: Can you add a comment explaining what this does and why it's necessary?

**Review by jonahkagan — APPROVED** [review]
