### PR TITLE
VxScan: fix test mode banner blipping out during scans

### LINKED ISSUE #5646: VxScan: in test mode, when scanning a ballot, the testing banner disappears
In test mode, when scanning a ballot, the testing banner disappears. Reappears at "insert your ballot" screen.

Issue automatically created from Slack feedback reported by ben: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1732478662282789?thread_ts=1732478662.282789&cid=CJU9MSC6S

### PR DESCRIPTION
**Pull request by adghayes**
## Overview

Closes #5646. We currently show the test mode banner when polls are not open and no one is authenticated, or when polls are open on the "Insert Your Ballot" screen. In other words, the main screens where the machine is just sitting there.

But we are not showing the banner on all the screens in the voter flow, which leads to weird behavior of the test mode banner blipping out while scanning the ballot and after acceptance, but then coming back. This PR adds the banner to all screens that are part of the `VoterScreen`. 

## Demo Video or Screenshot

https://github.com/user-attachments/assets/059779eb-ca09-4030-acc5-f86c44eaf4c8

### CODE REVIEW

File: apps/scan/frontend/src/components/layout.tsx [hunk 1]
```diff
@@ -30,11 +30,11 @@ export interface ScreenProps {
   hideBallotCount?: boolean;
   centerContent?: boolean;
   children: React.ReactNode;
-  isLiveMode?: boolean;
   infoBarMode?: InfoBarMode;
   hideInfoBar?: boolean;
   padded?: boolean;
   title?: React.ReactNode;
+  showTestModeBanner: boolean;
```
Comment (adghayes) [inline apps/scan/frontend/src/components/layout.tsx:37]: - changing the name, because sometimes it will be test mode but we don't want to show the banner
- making required, so when using the component we have to think about whether the test mode banner should show or not

**Review by kofi-q — APPROVED** [review]
