### PR TITLE
(fix: precinct-scanner): Show warning when machine needs backup before being unconfigured

### LINKED ISSUE #2051: nh-accuvote VxScan: cannot unconfigure
## Description
Unconfiguring never completes and continually presents a Loading... screen when unconfiguring VxScan loaded with the NH ballot package (f0b66d8a41). I cannot reproduce this issue with other ballot packages.

## Repro
1. Tested on main on 6/30
2. Configure VxScan with NH ballot package (f0b66d8a41)
3. Insert admin card, click unconfigure, and confirm
4. See loading screen

### PR DESCRIPTION
**Pull request by taravancil**
## Overview
Fixes #2051 

This disables unconfiguring the machine and switching to testing mode if a machine requires backup. It also adds warning messages to explain that backup is required.

## Demo Video or Screenshot

https://user-images.githubusercontent.com/7584833/177598380-844509a1-a2b5-4383-9cbf-b7938b3cce36.mov

## Testing Plan 
Added tests, manual testing.

## Checklist
- [x] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced.
- [x] I have added JSDoc comments to any newly introduced exports

- [x] I have added a screenshot and/or video to this PR to demo the change
- [x] I have added the "user_facing_change" label to this PR to automate an announcement in #machine-product-updates

### CODE REVIEW

File: frontends/precinct-scanner/src/screens/admin_screen.tsx [hunk 1]
```diff
@@ -179,6 +210,34 @@ export function AdminScreen({
           </div>
         </Bar>
       </Absolute>
+      {isShowingToggleLiveModeWarningModal && (
+        <Modal
+          content={
+            <Prose>
+              <h1>Export Backup to switch to Test Mode</h1>
```
Comment (arsalansufi) [inline frontends/precinct-scanner/src/screens/admin_screen.tsx:217]: I _think_ our headers, like our buttons, use title case, so "switch" should probably be capitalized

File: frontends/precinct-scanner/src/screens/admin_screen.tsx [hunk 2]
```diff
@@ -179,6 +210,34 @@ export function AdminScreen({
           </div>
         </Bar>
       </Absolute>
+      {isShowingToggleLiveModeWarningModal && (
```
Comment (arsalansufi) [inline frontends/precinct-scanner/src/screens/admin_screen.tsx:213]: Very minor! This boolean's name made me expect a modal that would prevent switching to live mode when it's actually preventing the reverse. Something like `isBackupBeforeTogglingTestModeWarningModalOpen` might be clearer (though a bit verbose)

**Review by arsalansufi — COMMENTED** [review]
Some quick minor thoughts!
