### PR TITLE
VxPollBook: update list of AAMVA issuers and mailing provinces to avoid crash

### LINKED ISSUE #7032: VxPollBook: prevent crash on licenses with unlisted provinces
Currently if you scan a Guam license with a name match you can crash the frontend. This was a known outcome of the state-setting work, this ticket is to track the follow-up.

### PR DESCRIPTION
**Pull request by adghayes**
## Overview

Closes #7032. 

## Demo Video or Screenshot

Tested manually.

## Testing Plan

No tests changed. Hard to test against a static list.

## Checklist

- [ ] I have prefixed my PR title with "VxDesign: ", "VxPollBook: ", or "HWTA: " if my change is specific to one of those products.
- [ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate for any new user actions.
- [ ] I have added the "user_facing_change" label to this PR, if relevant, to automate an announcement in #machine-product-updates.

### CODE REVIEW

File: apps/pollbook/barcode-scanner-daemon/src/aamva_jurisdictions.rs [hunk 1]
```diff
@@ -85,6 +86,7 @@ impl AamvaIssuingJurisdiction {
             Self::IA => "IA",
             Self::CO => "CO",
             Self::AR => "AR",
+            Self::KS => "KS",
```
Comment (kshen0) [inline apps/pollbook/barcode-scanner-daemon/src/aamva_jurisdictions.rs:89]: Good catch, thanks!

**Review by kshen0 — APPROVED** [review]
Thanks for taking this one
