### PR TITLE
Fix write-in adjudication image cropping for ballots with bubbles on the right

### LINKED ISSUE #4350: VxAdmin: WIA crops misaligned for right-aligned vxdesign ballots
https://votingworks.slack.com/archives/C060FEVB2L8/p1701822300936359

### PR DESCRIPTION
**Pull request by jonahkagan**
## Overview

Fixes #4350 

_Review by commit_

VxDesign always set the write-in image crop area based on a left-side bubble position, even for right-side bubble ballots. The fix is pretty simple - to flip the crop outset to the other side of the bubble.

This PR also adds some debugging tools to the VxDesign ballot viewer to help make it quicker to iterate on setting these particular values.

## Demo Video or Screenshot

Screenshot 2023-12-18 at 1 04 38 PM

https://github.com/votingworks/vxsuite/assets/530106/62b983b7-4391-4255-b79a-4244f7ce3c7d

Screenshot-VxAdmin-2023-12-18T21:19:24 888Z

## Testing Plan
- Visually confirmed with debugging tools in VxDesign
- Mock scanned a ballot image with VxCentralScan, loaded CVR into VxAdmin, visually confirmed (screenshot above)

## Checklist

- [ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced.

- [ ] I have added a screenshot and/or video to this PR to demo the change
- [ ] I have added the "user_facing_change" label to this PR to automate an announcement in #machine-product-updates

### CODE REVIEW

File: apps/design/frontend/src/ballot_viewer.tsx [hunk 1]
```diff
@@ -384,42 +485,84 @@ export function BallotViewer({
...
             document={ballotResult.ok().document}
-            grid={showGridLines ? grid : undefined}
+            debugInfo={{
+              ...debugFlags,
+              gridLayout: ballotResult.ok().gridLayout,
+              grid,
+            }}
           />
         )}
+        <DebugPanelWrapper>
```
Comment (eventualbuddha) [inline apps/design/frontend/src/ballot_viewer.tsx:514]: Consider extracting out of `BallotViewer` even if it stays in this file?

File: apps/design/frontend/src/ballot_viewer.tsx [hunk 2]
```diff
@@ -54,6 +56,19 @@ function SvgAnyElement({ element }: { element: AnyElement }) {
   }
 }
 
+interface DebugFlags {
+  // eslint-disable-next-line react/no-unused-prop-types
+  showGridLines: boolean;
+  // eslint-disable-next-line react/no-unused-prop-types
```
Comment (eventualbuddha) [inline apps/design/frontend/src/ballot_viewer.tsx:62]: You could get rid of these if you change the parameter type of `WriteInOptionBoxes` to `Omit<DebugInfo, keyof DebugFlags> & { width: number; height: number }`.

File: libs/hmpb/layout/src/layout.ts [hunk 3]
```diff
@@ -1683,12 +1683,20 @@ function layOutBallotHelper({
...
     gridLayout: {
       ballotStyleId: ballotStyle.id,
-      optionBoundsFromTargetMark: {
-        bottom: 1,
-        left: 1,
-        right: 9,
-        top: 1,
-      },
+      optionBoundsFromTargetMark:
+        bubblePosition === 'left'
```
Comment (eventualbuddha) [inline libs/hmpb/layout/src/layout.ts:1687]: I don't mind not having tests for the debug stuff, but this feels like it deserves a test. Unless you consider the changes to the fixtures as sufficient?

**Review by eventualbuddha — APPROVED** [review]

File: libs/hmpb/layout/src/layout.ts (hunk 3 above)
Comment (jonahkagan) [reply libs/hmpb/layout/src/layout.ts:1687]: I've generally been relying on the fixtures to test this. Your question is making me think about what would make for a good test of write-in cropping though. Maybe actually cropping an image of the ballot and snapshotting that so that if it changes, we'd be looking at a visual diff?

Comment (eventualbuddha) [reply libs/hmpb/layout/src/layout.ts:1687]: I do think that'd be a useful test.

File: apps/design/frontend/src/ballot_viewer.tsx (hunk 2 above)
Comment (jonahkagan) [reply apps/design/frontend/src/ballot_viewer.tsx]: 01cc133ba

File: apps/design/frontend/src/ballot_viewer.tsx (hunk 1 above)
Comment (jonahkagan) [reply apps/design/frontend/src/ballot_viewer.tsx]: 01cc133ba

**Review by eventualbuddha — APPROVED** [review]

File: libs/hmpb/layout/src/layout.ts (hunk 3 above)
Comment (jonahkagan) [reply libs/hmpb/layout/src/layout.ts:1687]: [089546e](https://github.com/votingworks/vxsuite/pull/4444/commits/089546ef1fffe684872e5faf342e9319961f7d00)
