### PR TITLE
VxPollBook: some post-QA quick fixes

### LINKED ISSUE #6774: VxPollBook: move identification check-in detail around
If someone checks in with an OOS DL, that currently shows up on the search page:

Image

This seems unnecessary, and the only reason it is that way is because there was no voter details page to add it to. @kshen0 has already added it to the voter details page, so it just needs to be removed.

### PR DESCRIPTION
**Pull request by adghayes**
## Overview

Addresses some of the issues I noticed in QA that were easy enough to fix. By commit:

1 & 2 - copy changes, mostly capitalizing the 'B' in VxPollBook, separating pollbook into poll book, and a few other small tweaks.
3 - reorder tabs in SA and EM screens to be more in descending importance
4 - add NH to list of states for mailing address updates
5 - fix visual glitch in network menu
6 - fix visual glitch with titled cards
7 - fix niche problem of voter searches maintaining their sort even when the precinct is changed. super corner case, but easy enough to fix

edit: added a few more commits

8 - remove "Check-In" from the poll worker side panel since it's the only entry, and unnecessary
9 - remove OOS DL info from the search screen, as it is TMI. Closes #6774.
10 - tweak how OOS DL information is shown on the voter details page

### CODE REVIEW

File: apps/pollbook/frontend/src/update_mailing_address_flow.tsx [hunk 1]
```diff
@@ -48,7 +48,7 @@ function createBlankMailingAddress(): VoterMailingAddressChangeRequest {
     mailingAddressLine2: '',
     mailingAddressLine3: '',
     mailingCityTown: '',
-    mailingState: 'NH',
+    mailingState: '',
```
Comment (adghayes) [inline apps/pollbook/frontend/src/update_mailing_address_flow.tsx:51]: for some reason the default mailing address was set to NH which, because NH didn't appear in the list, functioned exactly as if it were blank (as the function name suggests)

File: apps/pollbook/frontend/src/shared_components.tsx [hunk 2]
```diff
@@ -146,6 +146,7 @@ export const RequiredStaticInput = styled(StaticInput)`
 const TitleBar = styled.div`
   padding: 0.5rem 1rem;
   background-color: ${(p) => p.theme.colors.containerLow};
+  border-radius: ${(p) => p.theme.sizes.borderRadiusRem}rem;
```
[the remark this answers is not in the document]
Comment (adghayes) [reply apps/pollbook/frontend/src/shared_components.tsx]: Screenshot 2025-07-11 at 1 12 29 PM

Realized I accidentally changed the bottom border radii too, fixed.

File: apps/pollbook/frontend/src/nav_screen.tsx [hunk 3]
```diff
@@ -515,35 +515,6 @@ export const pollWorkerRoutes = {
...
-              </NavLink>
-            </NavListItem>
-          ))}
-        </NavList>
-      }
-    >
-      {children}
-    </NavScreen>
-  );
-}
```
Comment (adghayes) [inline apps/pollbook/frontend/src/nav_screen.tsx:546]: Screenshot-VxPollBook-2025-07-14T23:18:22 798Z
Screenshot-VxPollBook-2025-07-14T23:20:09 692Z

**Review by kshen0 — APPROVED** [review]
